//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vkSuite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vkSuite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;root domain=&quot;&quot;&gt;
        ///	&lt;emoji code=&quot;D83DDE0A&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE03&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE09&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE06&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE1C&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE0B&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE0D&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE0E&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE12&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE0F&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE14&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE22&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE2D&quot;&gt;&lt;/emoji&gt;
        ///	&lt;emoji code=&quot;D83DDE29&quot;&gt;&lt;/e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
    }
}
